name: "Try to build packages"

on:
  push:
    branches: [ master, main ]
  schedule:
    - cron: '30 0 * * *'

permissions:
  contents: read

jobs:
  r-update-cachix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Synching fork
      run: git clone https://github.com/NixOS/nixpkgs    

    - name: building icosa
      run: |
          cd nixpkgs/ 
          sed -i 's|enableHttp ? false|enableHttp ? true|g' pkgs/development/libraries/libxml2/default.nix
          nix-shell -I nixpkgs=. -p R rPackages.icosa 
